TYPE
	PlcOutputs : STRUCT
		ST70_ET200SP_CM_4xIO_Link_1 : ARRAY[0..31] OF BYTE;
		ST70_ET200SP_DQ_16x24VDC_0_5A_ST_1 : WORD;
		ST70_ET200SP_DQ_16x24VDC_0_5A_ST_2 : WORD;
		ST70_ET200SP_DQ_16x24VDC_0_5A_ST_3 : WORD;
		ST70_CPX_MPA1S_VMPA1_FB_EMS_8_8DO_1 : BYTE;
		ST70_CPX_MPA1S_VMPA1_FB_EMS_8_8DO_2 : BYTE;
		ST70_CPX_MPA1S_VMPA1_FB_EMS_8_8DO_3 : BYTE;
		ST70_CPX_MPA2S_VMPA2_FB_EMS_4_4DO_1 : BYTE;
		ST70_CPX_MPA1G_VMPA1_FB_EMG_8_8DO_3 : BYTE;
		ST70_1_DM260_PB_Acquisition_Control_1 : BYTE;
		ST70_1_DM260_PB_Results_Control_1 : BYTE;
		ST70_1_DM260_PB_Soft_Event_Control_1 : BYTE;
		ST70_1_DM260_PB_User_Data_64_bytes_1 : ARRAY[0..67] OF BYTE;
		ST70_2_DM260_PB_Acquisition_Control_1 : BYTE;
		ST70_2_DM260_PB_Results_Control_1 : BYTE;
		ST70_2_DM260_PB_Soft_Event_Control_1 : BYTE;
		ST70_2_DM260_PB_User_Data_64_bytes_1 : ARRAY[0..67] OF BYTE;
		ST70_3_DM260_PB_Acquisition_Control_1 : BYTE;
		ST70_3_DM260_PB_Results_Control_1 : BYTE;
		ST70_3_DM260_PB_Soft_Event_Control_1 : BYTE;
		ST70_3_DM260_PB_User_Data_64_bytes_1 : ARRAY[0..67] OF BYTE;
		ST70_1_DM260_EB_Acquisition_Control_1 : BYTE;
		ST70_1_DM260_EB_Results_Control_1 : BYTE;
		ST70_1_DM260_EB_Soft_Event_Control_1 : BYTE;
		ST70_1_DM260_EB_User_Data_64_bytes_1 : ARRAY[0..67] OF BYTE;
		ST70_2_DM260_EB_Acquisition_Control_1 : BYTE;
		ST70_2_DM260_EB_Results_Control_1 : BYTE;
		ST70_2_DM260_EB_Soft_Event_Control_1 : BYTE;
		ST70_2_DM260_EB_User_Data_64_bytes_1 : ARRAY[0..67] OF BYTE;
		ST70_3_DM260_EB_Acquisition_Control_1 : BYTE;
		ST70_3_DM260_EB_Results_Control_1 : BYTE;
		ST70_3_DM260_EB_Soft_Event_Control_1 : BYTE;
		ST70_3_DM260_EB_User_Data_64_bytes_1 : ARRAY[0..67] OF BYTE;
	END_STRUCT;
END_TYPE
