TYPE
	HwIdentifiers : WORD
	(
		PLC_1_Rail_0 :=	WORD#256,
		PLC_1 :=	WORD#48,
		PLC_1_Card_reader_writer_1 :=	WORD#51,
		PLC_1_CPU_display_1 :=	WORD#54,
		PLC_1_OPC_UA_1 :=	WORD#117,
		PLC_1_DP_interface_1 :=	WORD#60,
		PLC_1_PROFINET_interface_1 :=	WORD#64,
		PLC_1_PROFINET_interface_1_Port_1 :=	WORD#65,
		PLC_1_PROFINET_interface_1_Port_2 :=	WORD#66,
		PLC_1_PROFINET_interface_2 :=	WORD#72,
		PLC_1_PROFINET_interface_2_Port_1 :=	WORD#73,
		IO_device_1_Rack_0 :=	WORD#266,
		IO_device_1 :=	WORD#267,
		IO_device_1_IO_device_1 :=	WORD#258,
		IO_device_1_PROFINET_interface :=	WORD#259,
		IO_device_1_PROFINET_interface_Port_1 :=	WORD#260,
		IO_device_1_PROFINET_interface_Port_2 :=	WORD#261,
		IO_device_1_BA_2xRJ45 :=	WORD#260,
		IO_device_1_DI_8x24VDC_BA_1 :=	WORD#262,
		IO_device_1_DI_8x24VDC_BA_2 :=	WORD#263,
		IO_device_1_Server_module_1 :=	WORD#264,
		NONE:= WORD#0
	);
END_TYPE
