TYPE
	HwIdentifiers : WORD
	(
		PLC_2_Rail_0 :=	WORD#256,
		PLC_2 :=	WORD#48,
		PLC_2_Card_reader_writer_1 :=	WORD#51,
		PLC_2_CPU_display_1 :=	WORD#54,
		PLC_2_OPC_UA_1 :=	WORD#117,
		PLC_2_DP_interface_1 :=	WORD#60,
		PLC_2_PROFINET_interface_1 :=	WORD#64,
		PLC_2_PROFINET_interface_1_Port_1 :=	WORD#65,
		PLC_2_PROFINET_interface_1_Port_2 :=	WORD#66,
		PLC_2_PROFINET_interface_2 :=	WORD#72,
		PLC_2_PROFINET_interface_2_Port_1 :=	WORD#73,
		IO_device_2_Rack_0 :=	WORD#266,
		IO_device_2 :=	WORD#267,
		IO_device_2_IO_device_2 :=	WORD#258,
		IO_device_2_PROFINET_interface :=	WORD#259,
		IO_device_2_PROFINET_interface_Port_1 :=	WORD#260,
		IO_device_2_PROFINET_interface_Port_2 :=	WORD#261,
		IO_device_2_BA_2xRJ45 :=	WORD#260,
		IO_device_2_DI_8x24VDC_BA_1 :=	WORD#262,
		IO_device_2_DI_8x24VDC_BA_2 :=	WORD#263,
		IO_device_2_Server_module_1 :=	WORD#264,
		NONE:= WORD#0
	);
END_TYPE
