set ORIGINAL_PATH=%CD%
start /wait "Update" /D "%ORIGINAL_PATH%\HW_1516" "Update.bat" 
start /wait "Update" /D "%ORIGINAL_PATH%\HW_1516_reader" "Update.bat" 
start /wait "Update" /D "%ORIGINAL_PATH%\HW_2000482_V18" "Update.bat" 
start /wait "Update" /D "%ORIGINAL_PATH%\HW_2000528_main_V18" "Update.bat" 
start /wait "Update" /D "%ORIGINAL_PATH%\HW_2000528_ST43_V18" "Update.bat" 
start /wait "Update" /D "%ORIGINAL_PATH%\HW_2100068_montaz_menica_PSA_8HP_EL58_V18" "Update.bat" 
start /wait "Update" /D "%ORIGINAL_PATH%\HW_2200220OffsetBodu_V18" "Update.bat" 
start /wait "Update" /D "%ORIGINAL_PATH%\HW_2200330_V18" "Update.bat" 
start /wait "Update" /D "%ORIGINAL_PATH%\HW_DiscoverGroups" "Update.bat" 
start /wait "Update" /D "%ORIGINAL_PATH%\HW_Plc1518V3_CmmtAs" "Update.bat" 
start /wait "Update" /D "%ORIGINAL_PATH%\HW_Plc1518V3_Cognex" "Update.bat" 
start /wait "Update" /D "%ORIGINAL_PATH%\HW_Plc1518V3_Desoutter" "Update.bat" 
start /wait "Update" /D "%ORIGINAL_PATH%\HW_Plc1518V3_IndraDrive" "Update.bat" 
start /wait "Update" /D "%ORIGINAL_PATH%\HW_Shared" "Update.bat" 
